/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tgits.basic.javalin.app;

import io.javalin.Javalin;
import tgits.basic.javalin.app.greeting.controller.HelloController;
import tgits.basic.javalin.app.greeting.handler.WelcomeHandler;

public class JavalinGreeter {

    public static void main(String[] args) {
        Javalin app = Javalin.create().start(7000);

        app.get("/", new WelcomeHandler());

        app.get("/bonjour", ctx -> ctx.result("Bonjour"));

        HelloController helloController = new HelloController();
        app.get("/hello", helloController::getSimpleHello);

        app.get("/hello/:name", helloController::getNamedHello);

        app.get("/hola/json", helloController::getJsonHello);
    }
}
