/*
 * This source file was generated by the Gradle 'init' task
 */
package tgits.jline.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.showIntroMessage(), "app should have an intro message");
    }
}
