/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package tgits.algorithm.graph.core

import org.ejml.dense.row.RandomMatrices_DDRM
import org.ejml.simple.SimpleMatrix
import java.util.*


class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    println(App().greeting)
}
