types_pokemon = {
    0: "Normal",
    1: "Fighting",
    2: "Flying",
    3: "Poison",
    4: "Ground",
    5: "Rock",
    6: "Bug",
    7: "Ghost",
    8: "Steel",
    9: "Fire",
    10: "Water",
    11: "Grass",
    12: "Electric",
    13: "Psychic",
    14: "Ice",
    15: "Dragon",
    16: "Dark",
    17: "Fairy",
}

pokemon_by_id = {
    1: "Bulbasaur",
    2: "Ivysaur",
    3: "Venusaur",
    4: "Charmander",
    5: "Charmeleon",
    6: "Charizard",
    7: "Squirtle",
    8: "Wartortle",
    9: "Blastoise",
    10: "Caterpie",
    11: "Metapod",
    12: "Butterfree",
    13: "Weedle",
    14: "Kakuna",
    15: "Beedrill",
    16: "Pidgey",
    17: "Pidgeotto",
    18: "Pidgeot",
    19: "Rattata",
    20: "Raticate",
    21: "Spearow",
    22: "Fearow",
    23: "Ekans",
    24: "Arbok",
    25: "Pikachu",
    26: "Raichu",
    27: "Sandshrew",
    28: "Sandslash",
    29: "Nidoran♀",
    30: "Nidorina",
    31: "Nidoqueen",
    32: "Nidoran♂",
    33: "Nidorino",
    34: "Nidoking",
    35: "Clefairy",
    36: "Clefable",
    37: "Vulpix",
    38: "Ninetales",
    39: "Jigglypuff",
    40: "Wigglytuff",
    41: "Zubat",
    42: "Golbat",
    43: "Oddish",
    44: "Gloom",
    45: "Vileplume",
    46: "Paras",
    47: "Parasect",
    48: "Venonat",
    49: "Venomoth",
    50: "Diglett",
    51: "Dugtrio",
    52: "Meowth",
    53: "Persian",
    54: "Psyduck",
    55: "Golduck",
    56: "Mankey",
    57: "Primeape",
    58: "Growlithe",
    59: "Arcanine",
    60: "Poliwag",
    61: "Poliwhirl",
    62: "Poliwrath",
    63: "Abra",
    64: "Kadabra",
    65: "Alakazam",
    66: "Machop",
    67: "Machoke",
    68: "Machamp",
    69: "Bellsprout",
    70: "Weepinbell",
    71: "Victreebel",
    72: "Tentacool",
    73: "Tentacruel",
    74: "Geodude",
    75: "Graveler",
    76: "Golem",
    77: "Ponyta",
    78: "Rapidash",
    79: "Slowpoke",
    80: "Slowbro",
    81: "Magnemite",
    82: "Magneton",
    83: "Farfetch'd",
    84: "Doduo",
    85: "Dodrio",
    86: "Seel",
    87: "Dewgong",
    88: "Grimer",
    89: "Muk",
    90: "Shellder",
    91: "Cloyster",
    92: "Gastly",
    93: "Haunter",
    94: "Gengar",
    95: "Onix",
    96: "Drowzee",
    97: "Hypno",
    98: "Krabby",
    99: "Kingler",
    100: "Voltorb",
    101: "Electrode",
    102: "Exeggcute",
    103: "Exeggutor",
    104: "Cubone",
    105: "Marowak",
    106: "Hitmonlee",
    107: "Hitmonchan",
    108: "Lickitung",
    109: "Koffing",
    110: "Weezing",
    111: "Rhyhorn",
    112: "Rhydon",
    113: "Chansey",
    114: "Tangela",
    115: "Kangaskhan",
    116: "Horsea",
    117: "Seadra",
    118: "Goldeen",
    119: "Seaking",
    120: "Staryu",
    121: "Starmie",
    122: "Mr. Mime",
    123: "Scyther",
    124: "Jynx",
    125: "Electabuzz",
    126: "Magmar",
    127: "Pinsir",
    128: "Tauros",
    129: "Magikarp",
    130: "Gyarados",
    131: "Lapras",
    132: "Ditto",
    133: "Eevee",
    134: "Vaporeon",
    135: "Jolteon",
    136: "Flareon",
    137: "Porygon",
    138: "Omanyte",
    139: "Omastar",
    140: "Kabuto",
    141: "Kabutops",
    142: "Aerodactyl",
    143: "Snorlax",
    144: "Articuno",
    145: "Zapdos",
    146: "Moltres",
    147: "Dratini",
    148: "Dragonair",
    149: "Dragonite",
    150: "Mewtwo",
    151: "Mew",
    152: "Chikorita",
    153: "Bayleef",
    154: "Meganium",
    155: "Cyndaquil",
    156: "Quilava",
    157: "Typhlosion",
    158: "Totodile",
    159: "Croconaw",
    160: "Feraligatr",
    161: "Sentret",
    162: "Furret",
    163: "Hoothoot",
    164: "Noctowl",
    165: "Ledyba",
    166: "Ledian",
    167: "Spinarak",
    168: "Ariados",
    169: "Crobat",
    170: "Chinchou",
    171: "Lanturn",
    172: "Pichu",
    173: "Cleffa",
    174: "Igglybuff",
    175: "Togepi",
    176: "Togetic",
    177: "Natu",
    178: "Xatu",
    179: "Mareep",
    180: "Flaaffy",
    181: "Ampharos",
    182: "Bellossom",
    183: "Marill",
    184: "Azumarill",
    185: "Sudowoodo",
    186: "Politoed",
    187: "Hoppip",
    188: "Skiploom",
    189: "Jumpluff",
    190: "Aipom",
    191: "Sunkern",
    192: "Sunflora",
    193: "Yanma",
    194: "Wooper",
    195: "Quagsire",
    196: "Espeon",
    197: "Umbreon",
    198: "Murkrow",
    199: "Slowking",
    200: "Misdreavus",
    201: "Unown",
    202: "Wobbuffet",
    203: "Girafarig",
    204: "Pineco",
    205: "Forretress",
    206: "Dunsparce",
    207: "Gligar",
    208: "Steelix",
    209: "Snubbull",
    210: "Granbull",
    211: "Qwilfish",
    212: "Scizor",
    213: "Shuckle",
    214: "Heracross",
    215: "Sneasel",
    216: "Teddiursa",
    217: "Ursaring",
    218: "Slugma",
    219: "Magcargo",
    220: "Swinub",
    221: "Piloswine",
    222: "Corsola",
    223: "Remoraid",
    224: "Octillery",
    225: "Delibird",
    226: "Mantine",
    227: "Skarmory",
    228: "Houndour",
    229: "Houndoom",
    230: "Kingdra",
    231: "Phanpy",
    232: "Donphan",
    233: "Porygon2",
    234: "Stantler",
    235: "Smeargle",
    236: "Tyrogue",
    237: "Hitmontop",
    238: "Smoochum",
    239: "Elekid",
    240: "Magby",
    241: "Miltank",
    242: "Blissey",
    243: "Raikou",
    244: "Entei",
    245: "Suicune",
    246: "Larvitar",
    247: "Pupitar",
    248: "Tyranitar",
    249: "Lugia",
    250: "Ho-Oh",
    251: "Celebi",
    252: "Treecko",
    253: "Grovyle",
    254: "Sceptile",
    255: "Torchic",
    256: "Combusken",
    257: "Blaziken",
    258: "Mudkip",
    259: "Marshtomp",
    260: "Swampert",
    261: "Poochyena",
    262: "Mightyena",
    263: "Zigzagoon",
    264: "Linoone",
    265: "Wurmple",
    266: "Silcoon",
    267: "Beautifly",
    268: "Cascoon",
    269: "Dustox",
    270: "Lotad",
    271: "Lombre",
    272: "Ludicolo",
    273: "Seedot",
    274: "Nuzleaf",
    275: "Shiftry",
    276: "Taillow",
    277: "Swellow",
    278: "Wingull",
    279: "Pelipper",
    280: "Ralts",
    281: "Kirlia",
    282: "Gardevoir",
    283: "Surskit",
    284: "Masquerain",
    285: "Shroomish",
    286: "Breloom",
    287: "Slakoth",
    288: "Vigoroth",
    289: "Slaking",
    290: "Nincada",
    291: "Ninjask",
    292: "Shedinja",
    293: "Whismur",
    294: "Loudred",
    295: "Exploud",
    296: "Makuhita",
    297: "Hariyama",
    298: "Azurill",
    299: "Nosepass",
    300: "Skitty",
    301: "Delcatty",
    302: "Sableye",
    303: "Mawile",
    304: "Aron",
    305: "Lairon",
    306: "Aggron",
    307: "Meditite",
    308: "Medicham",
    309: "Electrike",
    310: "Manectric",
    311: "Plusle",
    312: "Minun",
    313: "Volbeat",
    314: "Illumise",
    315: "Roselia",
    316: "Gulpin",
    317: "Swalot",
    318: "Carvanha",
    319: "Sharpedo",
    320: "Wailmer",
    321: "Wailord",
    322: "Numel",
    323: "Camerupt",
    324: "Torkoal",
    325: "Spoink",
    326: "Grumpig",
    327: "Spinda",
    328: "Trapinch",
    329: "Vibrava",
    330: "Flygon",
    331: "Cacnea",
    332: "Cacturne",
    333: "Swablu",
    334: "Altaria",
    335: "Zangoose",
    336: "Seviper",
    337: "Lunatone",
    338: "Solrock",
    339: "Barboach",
    340: "Whiscash",
    341: "Corphish",
    342: "Crawdaunt",
    343: "Baltoy",
    344: "Claydol",
    345: "Lileep",
    346: "Cradily",
    347: "Anorith",
    348: "Armaldo",
    349: "Feebas",
    350: "Milotic",
    351: "Castform",
    352: "Kecleon",
    353: "Shuppet",
    354: "Banette",
    355: "Duskull",
    356: "Dusclops",
    357: "Tropius",
    358: "Chimecho",
    359: "Absol",
    360: "Wynaut",
    361: "Snorunt",
    362: "Glalie",
    363: "Spheal",
    364: "Sealeo",
    365: "Walrein",
    366: "Clamperl",
    367: "Huntail",
    368: "Gorebyss",
    369: "Relicanth",
    370: "Luvdisc",
    371: "Bagon",
    372: "Shelgon",
    373: "Salamence",
    374: "Beldum",
    375: "Metang",
    376: "Metagross",
    377: "Regirock",
    378: "Regice",
    379: "Registeel",
    380: "Latias",
    381: "Latios",
    382: "Kyogre",
    383: "Groudon",
    384: "Rayquaza",
    385: "Jirachi",
    386: "Deoxys",
    387: "Turtwig",
    388: "Grotle",
    389: "Torterra",
    390: "Chimchar",
    391: "Monferno",
    392: "Infernape",
    393: "Piplup",
    394: "Prinplup",
    395: "Empoleon",
    396: "Starly",
    397: "Staravia",
    398: "Staraptor",
    399: "Bidoof",
    400: "Bibarel",
    401: "Kricketot",
    402: "Kricketune",
    403: "Shinx",
    404: "Luxio",
    405: "Luxray",
    406: "Budew",
    407: "Roserade",
    408: "Cranidos",
    409: "Rampardos",
    410: "Shieldon",
    411: "Bastiodon",
    412: "Burmy",
    413: "Wormadam",
    414: "Mothim",
    415: "Combee",
    416: "Vespiquen",
    417: "Pachirisu",
    418: "Buizel",
    419: "Floatzel",
    420: "Cherubi",
    421: "Cherrim",
    422: "Shellos",
    423: "Gastrodon",
    424: "Ambipom",
    425: "Drifloon",
    426: "Drifblim",
    427: "Buneary",
    428: "Lopunny",
    429: "Mismagius",
    430: "Honchkrow",
    431: "Glameow",
    432: "Purugly",
    433: "Chingling",
    434: "Stunky",
    435: "Skuntank",
    436: "Bronzor",
    437: "Bronzong",
    438: "Bonsly",
    439: "Mime Jr.",
    440: "Happiny",
    441: "Chatot",
    442: "Spiritomb",
    443: "Gible",
    444: "Gabite",
    445: "Garchomp",
    446: "Munchlax",
    447: "Riolu",
    448: "Lucario",
    449: "Hippopotas",
    450: "Hippowdon",
    451: "Skorupi",
    452: "Drapion",
    453: "Croagunk",
    454: "Toxicroak",
    455: "Carnivine",
    456: "Finneon",
    457: "Lumineon",
    458: "Mantyke",
    459: "Snover",
    460: "Abomasnow",
    461: "Weavile",
    462: "Magnezone",
    463: "Lickilicky",
    464: "Rhyperior",
    465: "Tangrowth",
    466: "Electivire",
    467: "Magmortar",
    468: "Togekiss",
    469: "Yanmega",
    470: "Leafeon",
    471: "Glaceon",
    472: "Gliscor",
    473: "Mamoswine",
    474: "Porygon-Z",
    475: "Gallade",
    476: "Probopass",
    477: "Dusknoir",
    478: "Froslass",
    479: "Rotom",
    480: "Uxie",
    481: "Mesprit",
    482: "Azelf",
    483: "Dialga",
    484: "Palkia",
    485: "Heatran",
    486: "Regigigas",
    487: "Giratina",
    488: "Cresselia",
    489: "Phione",
    490: "Manaphy",
    491: "Darkrai",
    492: "Shaymin",
    493: "Arceus",
    494: "Victini",
    495: "Snivy",
    496: "Servine",
    497: "Serperior",
    498: "Tepig",
    499: "Pignite",
    500: "Emboar",
    501: "Oshawott",
    502: "Dewott",
    503: "Samurott",
    504: "Patrat",
    505: "Watchog",
    506: "Lillipup",
    507: "Herdier",
    508: "Stoutland",
    509: "Purrloin",
    510: "Liepard",
    511: "Pansage",
    512: "Simisage",
    513: "Pansear",
    514: "Simisear",
    515: "Panpour",
    516: "Simipour",
    517: "Munna",
    518: "Musharna",
    519: "Pidove",
    520: "Tranquill",
    521: "Unfezant",
    522: "Blitzle",
    523: "Zebstrika",
    524: "Roggenrola",
    525: "Boldore",
    526: "Gigalith",
    527: "Woobat",
    528: "Swoobat",
    529: "Drilbur",
    530: "Excadrill",
    531: "Audino",
    532: "Timburr",
    533: "Gurdurr",
    534: "Conkeldurr",
    535: "Tympole",
    536: "Palpitoad",
    537: "Seismitoad",
    538: "Throh",
    539: "Sawk",
    540: "Sewaddle",
    541: "Swadloon",
    542: "Leavanny",
    543: "Venipede",
    544: "Whirlipede",
    545: "Scolipede",
    546: "Cottonee",
    547: "Whimsicott",
    548: "Petilil",
    549: "Lilligant",
    550: "Basculin",
    551: "Sandile",
    552: "Krokorok",
    553: "Krookodile",
    554: "Darumaka",
    555: "Darmanitan",
    556: "Maractus",
    557: "Dwebble",
    558: "Crustle",
    559: "Scraggy",
    560: "Scrafty",
    561: "Sigilyph",
    562: "Yamask",
    563: "Cofagrigus",
    564: "Tirtouga",
    565: "Carracosta",
    566: "Archen",
    567: "Archeops",
    568: "Trubbish",
    569: "Garbodor",
    570: "Zorua",
    571: "Zoroark",
    572: "Minccino",
    573: "Cinccino",
    574: "Gothita",
    575: "Gothorita",
    576: "Gothitelle",
    577: "Solosis",
    578: "Duosion",
    579: "Reuniclus",
    580: "Ducklett",
    581: "Swanna",
    582: "Vanillite",
    583: "Vanillish",
    584: "Vanilluxe",
    585: "Deerling",
    586: "Sawsbuck",
    587: "Emolga",
    588: "Karrablast",
    589: "Escavalier",
    590: "Foongus",
    591: "Amoonguss",
    592: "Frillish",
    593: "Jellicent",
    594: "Alomomola",
    595: "Joltik",
    596: "Galvantula",
    597: "Ferroseed",
    598: "Ferrothorn",
    599: "Klink",
    600: "Klang",
    601: "Klinklang",
    602: "Tynamo",
    603: "Eelektrik",
    604: "Eelektross",
    605: "Elgyem",
    606: "Beheeyem",
    607: "Litwick",
    608: "Lampent",
    609: "Chandelure",
    610: "Axew",
    611: "Fraxure",
    612: "Haxorus",
    613: "Cubchoo",
    614: "Beartic",
    615: "Cryogonal",
    616: "Shelmet",
    617: "Accelgor",
    618: "Stunfisk",
    619: "Mienfoo",
    620: "Mienshao",
    621: "Druddigon",
    622: "Golett",
    623: "Golurk",
    624: "Pawniard",
    625: "Bisharp",
    626: "Bouffalant",
    627: "Rufflet",
    628: "Braviary",
    629: "Vullaby",
    630: "Mandibuzz",
    631: "Heatmor",
    632: "Durant",
    633: "Deino",
    634: "Zweilous",
    635: "Hydreigon",
    636: "Larvesta",
    637: "Volcarona",
    638: "Cobalion",
    639: "Terrakion",
    640: "Virizion",
    641: "Tornadus",
    642: "Thundurus",
    643: "Reshiram",
    644: "Zekrom",
    645: "Landorus",
    646: "Kyurem",
    647: "Keldeo",
    648: "Meloetta",
    649: "Genesect",
    650: "Chespin",
    651: "Quilladin",
    652: "Chesnaught",
    653: "Fennekin",
    654: "Braixen",
    655: "Delphox",
    656: "Froakie",
    657: "Frogadier",
    658: "Greninja",
    659: "Bunnelby",
    660: "Diggersby",
    661: "Fletchling",
    662: "Fletchinder",
    663: "Talonflame",
    664: "Scatterbug",
    665: "Spewpa",
    666: "Vivillon",
    667: "Litleo",
    668: "Pyroar",
    669: "Flabébé",
    670: "Floette",
    671: "Florges",
    672: "Skiddo",
    673: "Gogoat",
    674: "Pancham",
    675: "Pangoro",
    676: "Furfrou",
    677: "Espurr",
    678: "Meowstic",
    679: "Honedge",
    680: "Doublade",
    681: "Aegislash",
    682: "Spritzee",
    683: "Aromatisse",
    684: "Swirlix",
    685: "Slurpuff",
    686: "Inkay",
    687: "Malamar",
    688: "Binacle",
    689: "Barbaracle",
    690: "Skrelp",
    691: "Dragalge",
    692: "Clauncher",
    693: "Clawitzer",
    694: "Helioptile",
    695: "Heliolisk",
    696: "Tyrunt",
    697: "Tyrantrum",
    698: "Amaura",
    699: "Aurorus",
    700: "Sylveon",
    701: "Hawlucha",
    702: "Dedenne",
    703: "Carbink",
    704: "Goomy",
    705: "Sliggoo",
    706: "Goodra",
    707: "Klefki",
    708: "Phantump",
    709: "Trevenant",
    710: "Pumpkaboo",
    711: "Gourgeist",
    712: "Bergmite",
    713: "Avalugg",
    714: "Noibat",
    715: "Noivern",
    716: "Xerneas",
    717: "Yveltal",
    718: "Zygarde",
    719: "Diancie",
    720: "Hoopa",
    721: "Volcanion",
    722: "Rowlet",
    723: "Dartrix",
    724: "Decidueye",
    725: "Litten",
    726: "Torracat",
    727: "Incineroar",
    728: "Popplio",
    729: "Brionne",
    730: "Primarina",
    731: "Pikipek",
    732: "Trumbeak",
    733: "Toucannon",
    734: "Yungoos",
    735: "Gumshoos",
    736: "Grubbin",
    737: "Charjabug",
    738: "Vikavolt",
    739: "Crabrawler",
    740: "Crabominable",
    741: "Oricorio",
    742: "Cutiefly",
    743: "Ribombee",
    744: "Rockruff",
    745: "Lycanroc",
    746: "Wishiwashi",
    747: "Mareanie",
    748: "Toxapex",
    749: "Mudbray",
    750: "Mudsdale",
    751: "Dewpider",
    752: "Araquanid",
    753: "Fomantis",
    754: "Lurantis",
    755: "Morelull",
    756: "Shiinotic",
    757: "Salandit",
    758: "Salazzle",
    759: "Stufful",
    760: "Bewear",
    761: "Bounsweet",
    762: "Steenee",
    763: "Tsareena",
    764: "Comfey",
    765: "Oranguru",
    766: "Passimian",
    767: "Wimpod",
    768: "Golisopod",
    769: "Sandygast",
    770: "Palossand",
    771: "Pyukumuku",
    772: "Type: Null",
    773: "Silvally",
    774: "Minior",
    775: "Komala",
    776: "Turtonator",
    777: "Togedemaru",
    778: "Mimikyu",
    779: "Bruxish",
    780: "Drampa",
    781: "Dhelmise",
    782: "Jangmo-o",
    783: "Hakamo-o",
    784: "Kommo-o",
    785: "Tapu Koko",
    786: "Tapu Lele",
    787: "Tapu Bulu",
    788: "Tapu Fini",
    789: "Cosmog",
    790: "Cosmoem",
    791: "Solgaleo",
    792: "Lunala",
    793: "Nihilego",
    794: "Buzzwole",
    795: "Pheromosa",
    796: "Xurkitree",
    797: "Celesteela",
    798: "Kartana",
    799: "Guzzlord",
    800: "Necrozma",
    801: "Magearna",
    802: "Marshadow",
    803: "Poipole",
    804: "Naganadel",
    805: "Stakataka",
    806: "Blacephalon",
    807: "Zeraora",
    808: "Meltan",
    809: "Melmetal",
}

types_by_pokemon = {
    "Bulbasaur": ["Grass", "Poison"],
    "Ivysaur": ["Grass", "Poison"],
    "Venusaur": ["Grass", "Poison"],
    "Charmander": ["Fire"],
    "Charmeleon": ["Fire"],
    "Charizard": ["Fire", "Flying"],
    "Squirtle": ["Water"],
    "Wartortle": ["Water"],
    "Blastoise": ["Water"],
    "Caterpie": ["Bug"],
    "Metapod": ["Bug"],
    "Butterfree": ["Bug", "Flying"],
    "Weedle": ["Bug", "Poison"],
    "Kakuna": ["Bug", "Poison"],
    "Beedrill": ["Bug", "Poison"],
    "Pidgey": ["Normal", "Flying"],
    "Pidgeotto": ["Normal", "Flying"],
    "Pidgeot": ["Normal", "Flying"],
    "Rattata": ["Normal"],
    "Raticate": ["Normal"],
    "Spearow": ["Normal", "Flying"],
    "Fearow": ["Normal", "Flying"],
    "Ekans": ["Poison"],
    "Arbok": ["Poison"],
    "Pikachu": ["Electric"],
    "Raichu": ["Electric"],
    "Sandshrew": ["Ground"],
    "Sandslash": ["Ground"],
    "Nidoran♀": ["Poison"],
    "Nidorina": ["Poison"],
    "Nidoqueen": ["Poison", "Ground"],
    "Nidoran♂": ["Poison"],
    "Nidorino": ["Poison"],
    "Nidoking": ["Poison", "Ground"],
    "Clefairy": ["Fairy"],
    "Clefable": ["Fairy"],
    "Vulpix": ["Fire"],
    "Ninetales": ["Fire"],
    "Jigglypuff": ["Normal", "Fairy"],
    "Wigglytuff": ["Normal", "Fairy"],
    "Zubat": ["Poison", "Flying"],
    "Golbat": ["Poison", "Flying"],
    "Oddish": ["Grass", "Poison"],
    "Gloom": ["Grass", "Poison"],
    "Vileplume": ["Grass", "Poison"],
    "Paras": ["Bug", "Grass"],
    "Parasect": ["Bug", "Grass"],
    "Venonat": ["Bug", "Poison"],
    "Venomoth": ["Bug", "Poison"],
    "Diglett": ["Ground"],
    "Dugtrio": ["Ground"],
    "Meowth": ["Normal"],
    "Persian": ["Normal"],
    "Psyduck": ["Water"],
    "Golduck": ["Water"],
    "Mankey": ["Fighting"],
    "Primeape": ["Fighting"],
    "Growlithe": ["Fire"],
    "Arcanine": ["Fire"],
    "Poliwag": ["Water"],
    "Poliwhirl": ["Water"],
    "Poliwrath": ["Water", "Fighting"],
    "Abra": ["Psychic"],
    "Kadabra": ["Psychic"],
    "Alakazam": ["Psychic"],
    "Machop": ["Fighting"],
    "Machoke": ["Fighting"],
    "Machamp": ["Fighting"],
    "Bellsprout": ["Grass", "Poison"],
    "Weepinbell": ["Grass", "Poison"],
    "Victreebel": ["Grass", "Poison"],
    "Tentacool": ["Water", "Poison"],
    "Tentacruel": ["Water", "Poison"],
    "Geodude": ["Rock", "Ground"],
    "Graveler": ["Rock", "Ground"],
    "Golem": ["Rock", "Ground"],
    "Ponyta": ["Fire"],
    "Rapidash": ["Fire"],
    "Slowpoke": ["Water", "Psychic"],
    "Slowbro": ["Water", "Psychic"],
    "Magnemite": ["Electric", "Steel"],
    "Magneton": ["Electric", "Steel"],
    "Farfetch'd": ["Normal", "Flying"],
    "Doduo": ["Normal", "Flying"],
    "Dodrio": ["Normal", "Flying"],
    "Seel": ["Water"],
    "Dewgong": ["Water", "Ice"],
    "Grimer": ["Poison"],
    "Muk": ["Poison"],
    "Shellder": ["Water"],
    "Cloyster": ["Water", "Ice"],
    "Gastly": ["Ghost", "Poison"],
    "Haunter": ["Ghost", "Poison"],
    "Gengar": ["Ghost", "Poison"],
    "Onix": ["Rock", "Ground"],
    "Drowzee": ["Psychic"],
    "Hypno": ["Psychic"],
    "Krabby": ["Water"],
    "Kingler": ["Water"],
    "Voltorb": ["Electric"],
    "Electrode": ["Electric"],
    "Exeggcute": ["Grass", "Psychic"],
    "Exeggutor": ["Grass", "Psychic"],
    "Cubone": ["Ground"],
    "Marowak": ["Ground"],
    "Hitmonlee": ["Fighting"],
    "Hitmonchan": ["Fighting"],
    "Lickitung": ["Normal"],
    "Koffing": ["Poison"],
    "Weezing": ["Poison"],
    "Rhyhorn": ["Ground", "Rock"],
    "Rhydon": ["Ground", "Rock"],
    "Chansey": ["Normal"],
    "Tangela": ["Grass"],
    "Kangaskhan": ["Normal"],
    "Horsea": ["Water"],
    "Seadra": ["Water"],
    "Goldeen": ["Water"],
    "Seaking": ["Water"],
    "Staryu": ["Water"],
    "Starmie": ["Water", "Psychic"],
    "Mr. Mime": ["Psychic", "Fairy"],
    "Scyther": ["Bug", "Flying"],
    "Jynx": ["Ice", "Psychic"],
    "Electabuzz": ["Electric"],
    "Magmar": ["Fire"],
    "Pinsir": ["Bug"],
    "Tauros": ["Normal"],
    "Magikarp": ["Water"],
    "Gyarados": ["Water", "Flying"],
    "Lapras": ["Water", "Ice"],
    "Ditto": ["Normal"],
    "Eevee": ["Normal"],
    "Vaporeon": ["Water"],
    "Jolteon": ["Electric"],
    "Flareon": ["Fire"],
    "Porygon": ["Normal"],
    "Omanyte": ["Rock", "Water"],
    "Omastar": ["Rock", "Water"],
    "Kabuto": ["Rock", "Water"],
    "Kabutops": ["Rock", "Water"],
    "Aerodactyl": ["Rock", "Flying"],
    "Snorlax": ["Normal"],
    "Articuno": ["Ice", "Flying"],
    "Zapdos": ["Electric", "Flying"],
    "Moltres": ["Fire", "Flying"],
    "Dratini": ["Dragon"],
    "Dragonair": ["Dragon"],
    "Dragonite": ["Dragon", "Flying"],
    "Mewtwo": ["Psychic"],
    "Mew": ["Psychic"],
    "Chikorita": ["Grass"],
    "Bayleef": ["Grass"],
    "Meganium": ["Grass"],
    "Cyndaquil": ["Fire"],
    "Quilava": ["Fire"],
    "Typhlosion": ["Fire"],
    "Totodile": ["Water"],
    "Croconaw": ["Water"],
    "Feraligatr": ["Water"],
    "Sentret": ["Normal"],
    "Furret": ["Normal"],
    "Hoothoot": ["Normal", "Flying"],
    "Noctowl": ["Normal", "Flying"],
    "Ledyba": ["Bug", "Flying"],
    "Ledian": ["Bug", "Flying"],
    "Spinarak": ["Bug", "Poison"],
    "Ariados": ["Bug", "Poison"],
    "Crobat": ["Poison", "Flying"],
    "Chinchou": ["Water", "Electric"],
    "Lanturn": ["Water", "Electric"],
    "Pichu": ["Electric"],
    "Cleffa": ["Fairy"],
    "Igglybuff": ["Normal", "Fairy"],
    "Togepi": ["Fairy"],
    "Togetic": ["Fairy", "Flying"],
    "Natu": ["Psychic", "Flying"],
    "Xatu": ["Psychic", "Flying"],
    "Mareep": ["Electric"],
    "Flaaffy": ["Electric"],
    "Ampharos": ["Electric"],
    "Bellossom": ["Grass"],
    "Marill": ["Water", "Fairy"],
    "Azumarill": ["Water", "Fairy"],
    "Sudowoodo": ["Rock"],
    "Politoed": ["Water"],
    "Hoppip": ["Grass", "Flying"],
    "Skiploom": ["Grass", "Flying"],
    "Jumpluff": ["Grass", "Flying"],
    "Aipom": ["Normal"],
    "Sunkern": ["Grass"],
    "Sunflora": ["Grass"],
    "Yanma": ["Bug", "Flying"],
    "Wooper": ["Water", "Ground"],
    "Quagsire": ["Water", "Ground"],
    "Espeon": ["Psychic"],
    "Umbreon": ["Dark"],
    "Murkrow": ["Dark", "Flying"],
    "Slowking": ["Water", "Psychic"],
    "Misdreavus": ["Ghost"],
    "Unown": ["Psychic"],
    "Wobbuffet": ["Psychic"],
    "Girafarig": ["Normal", "Psychic"],
    "Pineco": ["Bug"],
    "Forretress": ["Bug", "Steel"],
    "Dunsparce": ["Normal"],
    "Gligar": ["Ground", "Flying"],
    "Steelix": ["Steel", "Ground"],
    "Snubbull": ["Fairy"],
    "Granbull": ["Fairy"],
    "Qwilfish": ["Water", "Poison"],
    "Scizor": ["Bug", "Steel"],
    "Shuckle": ["Bug", "Rock"],
    "Heracross": ["Bug", "Fighting"],
    "Sneasel": ["Dark", "Ice"],
    "Teddiursa": ["Normal"],
    "Ursaring": ["Normal"],
    "Slugma": ["Fire"],
    "Magcargo": ["Fire", "Rock"],
    "Swinub": ["Ice", "Ground"],
    "Piloswine": ["Ice", "Ground"],
    "Corsola": ["Water", "Rock"],
    "Remoraid": ["Water"],
    "Octillery": ["Water"],
    "Delibird": ["Ice", "Flying"],
    "Mantine": ["Water", "Flying"],
    "Skarmory": ["Steel", "Flying"],
    "Houndour": ["Dark", "Fire"],
    "Houndoom": ["Dark", "Fire"],
    "Kingdra": ["Water", "Dragon"],
    "Phanpy": ["Ground"],
    "Donphan": ["Ground"],
    "Porygon2": ["Normal"],
    "Stantler": ["Normal"],
    "Smeargle": ["Normal"],
    "Tyrogue": ["Fighting"],
    "Hitmontop": ["Fighting"],
    "Smoochum": ["Ice", "Psychic"],
    "Elekid": ["Electric"],
    "Magby": ["Fire"],
    "Miltank": ["Normal"],
    "Blissey": ["Normal"],
    "Raikou": ["Electric"],
    "Entei": ["Fire"],
    "Suicune": ["Water"],
    "Larvitar": ["Rock", "Ground"],
    "Pupitar": ["Rock", "Ground"],
    "Tyranitar": ["Rock", "Dark"],
    "Lugia": ["Psychic", "Flying"],
    "Ho-Oh": ["Fire", "Flying"],
    "Celebi": ["Psychic", "Grass"],
    "Treecko": ["Grass"],
    "Grovyle": ["Grass"],
    "Sceptile": ["Grass"],
    "Torchic": ["Fire"],
    "Combusken": ["Fire", "Fighting"],
    "Blaziken": ["Fire", "Fighting"],
    "Mudkip": ["Water"],
    "Marshtomp": ["Water", "Ground"],
    "Swampert": ["Water", "Ground"],
    "Poochyena": ["Dark"],
    "Mightyena": ["Dark"],
    "Zigzagoon": ["Normal"],
    "Linoone": ["Normal"],
    "Wurmple": ["Bug"],
    "Silcoon": ["Bug"],
    "Beautifly": ["Bug", "Flying"],
    "Cascoon": ["Bug"],
    "Dustox": ["Bug", "Poison"],
    "Lotad": ["Water", "Grass"],
    "Lombre": ["Water", "Grass"],
    "Ludicolo": ["Water", "Grass"],
    "Seedot": ["Grass"],
    "Nuzleaf": ["Grass", "Dark"],
    "Shiftry": ["Grass", "Dark"],
    "Taillow": ["Normal", "Flying"],
    "Swellow": ["Normal", "Flying"],
    "Wingull": ["Water", "Flying"],
    "Pelipper": ["Water", "Flying"],
    "Ralts": ["Psychic", "Fairy"],
    "Kirlia": ["Psychic", "Fairy"],
    "Gardevoir": ["Psychic", "Fairy"],
    "Surskit": ["Bug", "Water"],
    "Masquerain": ["Bug", "Flying"],
    "Shroomish": ["Grass"],
    "Breloom": ["Grass", "Fighting"],
    "Slakoth": ["Normal"],
    "Vigoroth": ["Normal"],
    "Slaking": ["Normal"],
    "Nincada": ["Bug", "Ground"],
    "Ninjask": ["Bug", "Flying"],
    "Shedinja": ["Bug", "Ghost"],
    "Whismur": ["Normal"],
    "Loudred": ["Normal"],
    "Exploud": ["Normal"],
    "Makuhita": ["Fighting"],
    "Hariyama": ["Fighting"],
    "Azurill": ["Normal", "Fairy"],
    "Nosepass": ["Rock"],
    "Skitty": ["Normal"],
    "Delcatty": ["Normal"],
    "Sableye": ["Dark", "Ghost"],
    "Mawile": ["Steel", "Fairy"],
    "Aron": ["Steel", "Rock"],
    "Lairon": ["Steel", "Rock"],
    "Aggron": ["Steel", "Rock"],
    "Meditite": ["Fighting", "Psychic"],
    "Medicham": ["Fighting", "Psychic"],
    "Electrike": ["Electric"],
    "Manectric": ["Electric"],
    "Plusle": ["Electric"],
    "Minun": ["Electric"],
    "Volbeat": ["Bug"],
    "Illumise": ["Bug"],
    "Roselia": ["Grass", "Poison"],
    "Gulpin": ["Poison"],
    "Swalot": ["Poison"],
    "Carvanha": ["Water", "Dark"],
    "Sharpedo": ["Water", "Dark"],
    "Wailmer": ["Water"],
    "Wailord": ["Water"],
    "Numel": ["Fire", "Ground"],
    "Camerupt": ["Fire", "Ground"],
    "Torkoal": ["Fire"],
    "Spoink": ["Psychic"],
    "Grumpig": ["Psychic"],
    "Spinda": ["Normal"],
    "Trapinch": ["Ground"],
    "Vibrava": ["Ground", "Dragon"],
    "Flygon": ["Ground", "Dragon"],
    "Cacnea": ["Grass"],
    "Cacturne": ["Grass", "Dark"],
    "Swablu": ["Normal", "Flying"],
    "Altaria": ["Dragon", "Flying"],
    "Zangoose": ["Normal"],
    "Seviper": ["Poison"],
    "Lunatone": ["Rock", "Psychic"],
    "Solrock": ["Rock", "Psychic"],
    "Barboach": ["Water", "Ground"],
    "Whiscash": ["Water", "Ground"],
    "Corphish": ["Water"],
    "Crawdaunt": ["Water", "Dark"],
    "Baltoy": ["Ground", "Psychic"],
    "Claydol": ["Ground", "Psychic"],
    "Lileep": ["Rock", "Grass"],
    "Cradily": ["Rock", "Grass"],
    "Anorith": ["Rock", "Bug"],
    "Armaldo": ["Rock", "Bug"],
    "Feebas": ["Water"],
    "Milotic": ["Water"],
    "Castform": ["Normal"],
    "Kecleon": ["Normal"],
    "Shuppet": ["Ghost"],
    "Banette": ["Ghost"],
    "Duskull": ["Ghost"],
    "Dusclops": ["Ghost"],
    "Tropius": ["Grass", "Flying"],
    "Chimecho": ["Psychic"],
    "Absol": ["Dark"],
    "Wynaut": ["Psychic"],
    "Snorunt": ["Ice"],
    "Glalie": ["Ice"],
    "Spheal": ["Ice", "Water"],
    "Sealeo": ["Ice", "Water"],
    "Walrein": ["Ice", "Water"],
    "Clamperl": ["Water"],
    "Huntail": ["Water"],
    "Gorebyss": ["Water"],
    "Relicanth": ["Water", "Rock"],
    "Luvdisc": ["Water"],
    "Bagon": ["Dragon"],
    "Shelgon": ["Dragon"],
    "Salamence": ["Dragon", "Flying"],
    "Beldum": ["Steel", "Psychic"],
    "Metang": ["Steel", "Psychic"],
    "Metagross": ["Steel", "Psychic"],
    "Regirock": ["Rock"],
    "Regice": ["Ice"],
    "Registeel": ["Steel"],
    "Latias": ["Dragon", "Psychic"],
    "Latios": ["Dragon", "Psychic"],
    "Kyogre": ["Water"],
    "Groudon": ["Ground"],
    "Rayquaza": ["Dragon", "Flying"],
    "Jirachi": ["Steel", "Psychic"],
    "Deoxys": ["Psychic"],
    "Turtwig": ["Grass"],
    "Grotle": ["Grass"],
    "Torterra": ["Grass", "Ground"],
    "Chimchar": ["Fire"],
    "Monferno": ["Fire", "Fighting"],
    "Infernape": ["Fire", "Fighting"],
    "Piplup": ["Water"],
    "Prinplup": ["Water"],
    "Empoleon": ["Water", "Steel"],
    "Starly": ["Normal", "Flying"],
    "Staravia": ["Normal", "Flying"],
    "Staraptor": ["Normal", "Flying"],
    "Bidoof": ["Normal"],
    "Bibarel": ["Normal", "Water"],
    "Kricketot": ["Bug"],
    "Kricketune": ["Bug"],
    "Shinx": ["Electric"],
    "Luxio": ["Electric"],
    "Luxray": ["Electric"],
    "Budew": ["Grass", "Poison"],
    "Roserade": ["Grass", "Poison"],
    "Cranidos": ["Rock"],
    "Rampardos": ["Rock"],
    "Shieldon": ["Rock", "Steel"],
    "Bastiodon": ["Rock", "Steel"],
    "Burmy": ["Bug"],
    "Wormadam": ["Bug", "Grass"],
    "Mothim": ["Bug", "Flying"],
    "Combee": ["Bug", "Flying"],
    "Vespiquen": ["Bug", "Flying"],
    "Pachirisu": ["Electric"],
    "Buizel": ["Water"],
    "Floatzel": ["Water"],
    "Cherubi": ["Grass"],
    "Cherrim": ["Grass"],
    "Shellos": ["Water"],
    "Gastrodon": ["Water", "Ground"],
    "Ambipom": ["Normal"],
    "Drifloon": ["Ghost", "Flying"],
    "Drifblim": ["Ghost", "Flying"],
    "Buneary": ["Normal"],
    "Lopunny": ["Normal"],
    "Mismagius": ["Ghost"],
    "Honchkrow": ["Dark", "Flying"],
    "Glameow": ["Normal"],
    "Purugly": ["Normal"],
    "Chingling": ["Psychic"],
    "Stunky": ["Poison", "Dark"],
    "Skuntank": ["Poison", "Dark"],
    "Bronzor": ["Steel", "Psychic"],
    "Bronzong": ["Steel", "Psychic"],
    "Bonsly": ["Rock"],
    "Mime Jr.": ["Psychic", "Fairy"],
    "Happiny": ["Normal"],
    "Chatot": ["Normal", "Flying"],
    "Spiritomb": ["Ghost", "Dark"],
    "Gible": ["Dragon", "Ground"],
    "Gabite": ["Dragon", "Ground"],
    "Garchomp": ["Dragon", "Ground"],
    "Munchlax": ["Normal"],
    "Riolu": ["Fighting"],
    "Lucario": ["Fighting", "Steel"],
    "Hippopotas": ["Ground"],
    "Hippowdon": ["Ground"],
    "Skorupi": ["Poison", "Bug"],
    "Drapion": ["Poison", "Dark"],
    "Croagunk": ["Poison", "Fighting"],
    "Toxicroak": ["Poison", "Fighting"],
    "Carnivine": ["Grass"],
    "Finneon": ["Water"],
    "Lumineon": ["Water"],
    "Mantyke": ["Water", "Flying"],
    "Snover": ["Grass", "Ice"],
    "Abomasnow": ["Grass", "Ice"],
    "Weavile": ["Dark", "Ice"],
    "Magnezone": ["Electric", "Steel"],
    "Lickilicky": ["Normal"],
    "Rhyperior": ["Ground", "Rock"],
    "Tangrowth": ["Grass"],
    "Electivire": ["Electric"],
    "Magmortar": ["Fire"],
    "Togekiss": ["Fairy", "Flying"],
    "Yanmega": ["Bug", "Flying"],
    "Leafeon": ["Grass"],
    "Glaceon": ["Ice"],
    "Gliscor": ["Ground", "Flying"],
    "Mamoswine": ["Ice", "Ground"],
    "Porygon-Z": ["Normal"],
    "Gallade": ["Psychic", "Fighting"],
    "Probopass": ["Rock", "Steel"],
    "Dusknoir": ["Ghost"],
    "Froslass": ["Ice", "Ghost"],
    "Rotom": ["Electric", "Ghost"],
    "Uxie": ["Psychic"],
    "Mesprit": ["Psychic"],
    "Azelf": ["Psychic"],
    "Dialga": ["Steel", "Dragon"],
    "Palkia": ["Water", "Dragon"],
    "Heatran": ["Fire", "Steel"],
    "Regigigas": ["Normal"],
    "Giratina": ["Ghost", "Dragon"],
    "Cresselia": ["Psychic"],
    "Phione": ["Water"],
    "Manaphy": ["Water"],
    "Darkrai": ["Dark"],
    "Shaymin": ["Grass"],
    "Arceus": ["Normal"],
    "Victini": ["Psychic", "Fire"],
    "Snivy": ["Grass"],
    "Servine": ["Grass"],
    "Serperior": ["Grass"],
    "Tepig": ["Fire"],
    "Pignite": ["Fire", "Fighting"],
    "Emboar": ["Fire", "Fighting"],
    "Oshawott": ["Water"],
    "Dewott": ["Water"],
    "Samurott": ["Water"],
    "Patrat": ["Normal"],
    "Watchog": ["Normal"],
    "Lillipup": ["Normal"],
    "Herdier": ["Normal"],
    "Stoutland": ["Normal"],
    "Purrloin": ["Dark"],
    "Liepard": ["Dark"],
    "Pansage": ["Grass"],
    "Simisage": ["Grass"],
    "Pansear": ["Fire"],
    "Simisear": ["Fire"],
    "Panpour": ["Water"],
    "Simipour": ["Water"],
    "Munna": ["Psychic"],
    "Musharna": ["Psychic"],
    "Pidove": ["Normal", "Flying"],
    "Tranquill": ["Normal", "Flying"],
    "Unfezant": ["Normal", "Flying"],
    "Blitzle": ["Electric"],
    "Zebstrika": ["Electric"],
    "Roggenrola": ["Rock"],
    "Boldore": ["Rock"],
    "Gigalith": ["Rock"],
    "Woobat": ["Psychic", "Flying"],
    "Swoobat": ["Psychic", "Flying"],
    "Drilbur": ["Ground"],
    "Excadrill": ["Ground", "Steel"],
    "Audino": ["Normal"],
    "Timburr": ["Fighting"],
    "Gurdurr": ["Fighting"],
    "Conkeldurr": ["Fighting"],
    "Tympole": ["Water"],
    "Palpitoad": ["Water", "Ground"],
    "Seismitoad": ["Water", "Ground"],
    "Throh": ["Fighting"],
    "Sawk": ["Fighting"],
    "Sewaddle": ["Bug", "Grass"],
    "Swadloon": ["Bug", "Grass"],
    "Leavanny": ["Bug", "Grass"],
    "Venipede": ["Bug", "Poison"],
    "Whirlipede": ["Bug", "Poison"],
    "Scolipede": ["Bug", "Poison"],
    "Cottonee": ["Grass", "Fairy"],
    "Whimsicott": ["Grass", "Fairy"],
    "Petilil": ["Grass"],
    "Lilligant": ["Grass"],
    "Basculin": ["Water"],
    "Sandile": ["Ground", "Dark"],
    "Krokorok": ["Ground", "Dark"],
    "Krookodile": ["Ground", "Dark"],
    "Darumaka": ["Fire"],
    "Darmanitan": ["Fire"],
    "Maractus": ["Grass"],
    "Dwebble": ["Bug", "Rock"],
    "Crustle": ["Bug", "Rock"],
    "Scraggy": ["Dark", "Fighting"],
    "Scrafty": ["Dark", "Fighting"],
    "Sigilyph": ["Psychic", "Flying"],
    "Yamask": ["Ghost"],
    "Cofagrigus": ["Ghost"],
    "Tirtouga": ["Water", "Rock"],
    "Carracosta": ["Water", "Rock"],
    "Archen": ["Rock", "Flying"],
    "Archeops": ["Rock", "Flying"],
    "Trubbish": ["Poison"],
    "Garbodor": ["Poison"],
    "Zorua": ["Dark"],
    "Zoroark": ["Dark"],
    "Minccino": ["Normal"],
    "Cinccino": ["Normal"],
    "Gothita": ["Psychic"],
    "Gothorita": ["Psychic"],
    "Gothitelle": ["Psychic"],
    "Solosis": ["Psychic"],
    "Duosion": ["Psychic"],
    "Reuniclus": ["Psychic"],
    "Ducklett": ["Water", "Flying"],
    "Swanna": ["Water", "Flying"],
    "Vanillite": ["Ice"],
    "Vanillish": ["Ice"],
    "Vanilluxe": ["Ice"],
    "Deerling": ["Normal", "Grass"],
    "Sawsbuck": ["Normal", "Grass"],
    "Emolga": ["Electric", "Flying"],
    "Karrablast": ["Bug"],
    "Escavalier": ["Bug", "Steel"],
    "Foongus": ["Grass", "Poison"],
    "Amoonguss": ["Grass", "Poison"],
    "Frillish": ["Water", "Ghost"],
    "Jellicent": ["Water", "Ghost"],
    "Alomomola": ["Water"],
    "Joltik": ["Bug", "Electric"],
    "Galvantula": ["Bug", "Electric"],
    "Ferroseed": ["Grass", "Steel"],
    "Ferrothorn": ["Grass", "Steel"],
    "Klink": ["Steel"],
    "Klang": ["Steel"],
    "Klinklang": ["Steel"],
    "Tynamo": ["Electric"],
    "Eelektrik": ["Electric"],
    "Eelektross": ["Electric"],
    "Elgyem": ["Psychic"],
    "Beheeyem": ["Psychic"],
    "Litwick": ["Ghost", "Fire"],
    "Lampent": ["Ghost", "Fire"],
    "Chandelure": ["Ghost", "Fire"],
    "Axew": ["Dragon"],
    "Fraxure": ["Dragon"],
    "Haxorus": ["Dragon"],
    "Cubchoo": ["Ice"],
    "Beartic": ["Ice"],
    "Cryogonal": ["Ice"],
    "Shelmet": ["Bug"],
    "Accelgor": ["Bug"],
    "Stunfisk": ["Ground", "Electric"],
    "Mienfoo": ["Fighting"],
    "Mienshao": ["Fighting"],
    "Druddigon": ["Dragon"],
    "Golett": ["Ground", "Ghost"],
    "Golurk": ["Ground", "Ghost"],
    "Pawniard": ["Dark", "Steel"],
    "Bisharp": ["Dark", "Steel"],
    "Bouffalant": ["Normal"],
    "Rufflet": ["Normal", "Flying"],
    "Braviary": ["Normal", "Flying"],
    "Vullaby": ["Dark", "Flying"],
    "Mandibuzz": ["Dark", "Flying"],
    "Heatmor": ["Fire"],
    "Durant": ["Bug", "Steel"],
    "Deino": ["Dark", "Dragon"],
    "Zweilous": ["Dark", "Dragon"],
    "Hydreigon": ["Dark", "Dragon"],
    "Larvesta": ["Bug", "Fire"],
    "Volcarona": ["Bug", "Fire"],
    "Cobalion": ["Steel", "Fighting"],
    "Terrakion": ["Rock", "Fighting"],
    "Virizion": ["Grass", "Fighting"],
    "Tornadus": ["Flying"],
    "Thundurus": ["Electric", "Flying"],
    "Reshiram": ["Dragon", "Fire"],
    "Zekrom": ["Dragon", "Electric"],
    "Landorus": ["Ground", "Flying"],
    "Kyurem": ["Dragon", "Ice"],
    "Keldeo": ["Water", "Fighting"],
    "Meloetta": ["Normal", "Psychic"],
    "Genesect": ["Bug", "Steel"],
    "Chespin": ["Grass"],
    "Quilladin": ["Grass"],
    "Chesnaught": ["Grass", "Fighting"],
    "Fennekin": ["Fire"],
    "Braixen": ["Fire"],
    "Delphox": ["Fire", "Psychic"],
    "Froakie": ["Water"],
    "Frogadier": ["Water"],
    "Greninja": ["Water", "Dark"],
    "Bunnelby": ["Normal"],
    "Diggersby": ["Normal", "Ground"],
    "Fletchling": ["Normal", "Flying"],
    "Fletchinder": ["Fire", "Flying"],
    "Talonflame": ["Fire", "Flying"],
    "Scatterbug": ["Bug"],
    "Spewpa": ["Bug"],
    "Vivillon": ["Bug", "Flying"],
    "Litleo": ["Fire", "Normal"],
    "Pyroar": ["Fire", "Normal"],
    "Flabébé": ["Fairy"],
    "Floette": ["Fairy"],
    "Florges": ["Fairy"],
    "Skiddo": ["Grass"],
    "Gogoat": ["Grass"],
    "Pancham": ["Fighting"],
    "Pangoro": ["Fighting", "Dark"],
    "Furfrou": ["Normal"],
    "Espurr": ["Psychic"],
    "Meowstic": ["Psychic"],
    "Honedge": ["Steel", "Ghost"],
    "Doublade": ["Steel", "Ghost"],
    "Aegislash": ["Steel", "Ghost"],
    "Spritzee": ["Fairy"],
    "Aromatisse": ["Fairy"],
    "Swirlix": ["Fairy"],
    "Slurpuff": ["Fairy"],
    "Inkay": ["Dark", "Psychic"],
    "Malamar": ["Dark", "Psychic"],
    "Binacle": ["Rock", "Water"],
    "Barbaracle": ["Rock", "Water"],
    "Skrelp": ["Poison", "Water"],
    "Dragalge": ["Poison", "Dragon"],
    "Clauncher": ["Water"],
    "Clawitzer": ["Water"],
    "Helioptile": ["Electric", "Normal"],
    "Heliolisk": ["Electric", "Normal"],
    "Tyrunt": ["Rock", "Dragon"],
    "Tyrantrum": ["Rock", "Dragon"],
    "Amaura": ["Rock", "Ice"],
    "Aurorus": ["Rock", "Ice"],
    "Sylveon": ["Fairy"],
    "Hawlucha": ["Fighting", "Flying"],
    "Dedenne": ["Electric", "Fairy"],
    "Carbink": ["Rock", "Fairy"],
    "Goomy": ["Dragon"],
    "Sliggoo": ["Dragon"],
    "Goodra": ["Dragon"],
    "Klefki": ["Steel", "Fairy"],
    "Phantump": ["Ghost", "Grass"],
    "Trevenant": ["Ghost", "Grass"],
    "Pumpkaboo": ["Ghost", "Grass"],
    "Gourgeist": ["Ghost", "Grass"],
    "Bergmite": ["Ice"],
    "Avalugg": ["Ice"],
    "Noibat": ["Flying", "Dragon"],
    "Noivern": ["Flying", "Dragon"],
    "Xerneas": ["Fairy"],
    "Yveltal": ["Dark", "Flying"],
    "Zygarde": ["Dragon", "Ground"],
    "Diancie": ["Rock", "Fairy"],
    "Hoopa": ["Psychic", "Ghost"],
    "Volcanion": ["Fire", "Water"],
    "Rowlet": ["Grass", "Flying"],
    "Dartrix": ["Grass", "Flying"],
    "Decidueye": ["Grass", "Ghost"],
    "Litten": ["Fire"],
    "Torracat": ["Fire"],
    "Incineroar": ["Fire", "Dark"],
    "Popplio": ["Water"],
    "Brionne": ["Water"],
    "Primarina": ["Water", "Fairy"],
    "Pikipek": ["Normal", "Flying"],
    "Trumbeak": ["Normal", "Flying"],
    "Toucannon": ["Normal", "Flying"],
    "Yungoos": ["Normal"],
    "Gumshoos": ["Normal"],
    "Grubbin": ["Bug"],
    "Charjabug": ["Bug", "Electric"],
    "Vikavolt": ["Bug", "Electric"],
    "Crabrawler": ["Fighting"],
    "Crabominable": ["Fighting", "Ice"],
    "Oricorio": ["Fire", "Flying"],
    "Cutiefly": ["Bug", "Fairy"],
    "Ribombee": ["Bug", "Fairy"],
    "Rockruff": ["Rock"],
    "Lycanroc": ["Rock"],
    "Wishiwashi": ["Water"],
    "Mareanie": ["Poison", "Water"],
    "Toxapex": ["Poison", "Water"],
    "Mudbray": ["Ground"],
    "Mudsdale": ["Ground"],
    "Dewpider": ["Water", "Bug"],
    "Araquanid": ["Water", "Bug"],
    "Fomantis": ["Grass"],
    "Lurantis": ["Grass"],
    "Morelull": ["Grass", "Fairy"],
    "Shiinotic": ["Grass", "Fairy"],
    "Salandit": ["Poison", "Fire"],
    "Salazzle": ["Poison", "Fire"],
    "Stufful": ["Normal", "Fighting"],
    "Bewear": ["Normal", "Fighting"],
    "Bounsweet": ["Grass"],
    "Steenee": ["Grass"],
    "Tsareena": ["Grass"],
    "Comfey": ["Fairy"],
    "Oranguru": ["Normal", "Psychic"],
    "Passimian": ["Fighting"],
    "Wimpod": ["Bug", "Water"],
    "Golisopod": ["Bug", "Water"],
    "Sandygast": ["Ghost", "Ground"],
    "Palossand": ["Ghost", "Ground"],
    "Pyukumuku": ["Water"],
    "Type: Null": ["Normal"],
    "Silvally": ["Normal"],
    "Minior": ["Rock", "Flying"],
    "Komala": ["Normal"],
    "Turtonator": ["Fire", "Dragon"],
    "Togedemaru": ["Electric", "Steel"],
    "Mimikyu": ["Ghost", "Fairy"],
    "Bruxish": ["Water", "Psychic"],
    "Drampa": ["Normal", "Dragon"],
    "Dhelmise": ["Ghost", "Grass"],
    "Jangmo-o": ["Dragon"],
    "Hakamo-o": ["Dragon", "Fighting"],
    "Kommo-o": ["Dragon", "Fighting"],
    "Tapu Koko": ["Electric", "Fairy"],
    "Tapu Lele": ["Psychic", "Fairy"],
    "Tapu Bulu": ["Grass", "Fairy"],
    "Tapu Fini": ["Water", "Fairy"],
    "Cosmog": ["Psychic"],
    "Cosmoem": ["Psychic"],
    "Solgaleo": ["Psychic", "Steel"],
    "Lunala": ["Psychic", "Ghost"],
    "Nihilego": ["Rock", "Poison"],
    "Buzzwole": ["Bug", "Fighting"],
    "Pheromosa": ["Bug", "Fighting"],
    "Xurkitree": ["Electric"],
    "Celesteela": ["Steel", "Flying"],
    "Kartana": ["Grass", "Steel"],
    "Guzzlord": ["Dark", "Dragon"],
    "Necrozma": ["Psychic"],
    "Magearna": ["Steel", "Fairy"],
    "Marshadow": ["Fighting", "Ghost"],
    "Poipole": ["Poison"],
    "Naganadel": ["Poison", "Dragon"],
    "Stakataka": ["Rock", "Steel"],
    "Blacephalon": ["Fire", "Ghost"],
    "Zeraora": ["Electric"],
    "Meltan": ["Steel"],
    "Melmetal": ["Steel"],
}
