import io.reactivex.Flowable;
import io.reactivex.Observable;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        Observable.just("Hello RxJava and Reactive Programming with Observable").subscribe(System.out::println);
        Flowable.just("Hello RxJava and Reactive Programming with Flowable").subscribe(System.out::println);
    }
}
