/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package tgits.algorithm.graph.core

import org.junit.jupiter.api.Test
import kotlin.test.junit5.JUnit5Asserter.assertNotNull

class AppTest {
    @Test
    fun testAppHasAGreeting() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
