/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tgits.basic.javalin.app;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class JavalinGreeterTest {
    @Test void appHasAGreeting() {
        JavalinGreeter classUnderTest = new JavalinGreeter();
        assertNotNull(classUnderTest);
    }
}
