name: calendar_server
description: Calendar server implementation
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  args: ^1.6.0
  calendar_shared:
    path: ../calendar_shared
  sembast: ^2.4.5
  shelf: ^0.7.7
  shelf_router: ^0.7.2

dev_dependencies:
  pedantic: ^1.9.0
