/*
 * This source file was generated by the Gradle 'init' task
 */
package tgits.jline.example;

import org.jline.reader.LineReader;
import org.jline.reader.LineReaderBuilder;
import org.jline.terminal.Terminal;
import org.jline.terminal.TerminalBuilder;

public class App {
    public String showIntroMessage() {
        return "Example of using JLine in a Java application.";
    }

    public static void main(String[] args) {
        System.out.println(new App().showIntroMessage());

        // First Create a terminal
        //As terminal implements Closeable we can use a try-with-resources pattens
        try(Terminal terminal = TerminalBuilder.builder()
                .system(true)
                .build()) {


            // Create line reader
            LineReader reader = LineReaderBuilder.builder()
                    .terminal(terminal)
                    .build();

            // Prompt and read input
            String line = reader.readLine("JLine > ");

            // Print the result
            System.out.println("You entered: " + line);

            String password = reader.readLine("> ", null, '#', null);
            System.out.println("You entered the password: " + password);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
