import turtle

print("La tortue est en position : ", str(turtle.position()))
turtle.color('red', 'yellow')
turtle.begin_fill()
turtle.pendown()
turtle.forward(200)
print("La tortue est en position : ", str(turtle.position()))
turtle.left(90)
turtle.forward(200)
print("La tortue est en position : ", str(turtle.position()))
turtle.left(90)
turtle.forward(200)
print("La tortue est en position : ", str(turtle.position()))
turtle.left(90)
turtle.forward(200)
turtle.end_fill()
turtle.hideturtle()
turtle.done()