/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package skynet_revolution_ep1

import kotlin.test.Test
import kotlin.test.assertTrue

class AppTest {
    @Test
    fun testExample() {
        assertTrue(true)
    }
}
